port: 8083
index: 1
status:
  port: 8084
  user: "user"
  password: "password"
pidfile: "/tmp/router.pid"
# session key should be a string of length 32
sessionkey: "14fbc303b76bacd1e0a3ab641c11d114"
nats:
  uri: "nats://nats:nats@localhost:4222"
logging:
  level: debug
  file: /tmp/router.log
  syslog: false
  # TODO: add steno web interface
